import type { Metadata } from "next";

import "./globals.css";
import ReduxProvider from "./Provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "ShopHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
        {children}
        <Toaster position="bottom-right" richColors/>
        </ReduxProvider>
        </body>
    </html>
  );
}
